name: '🐞 Bug Report'
description: 'Report an issue to help the project improve.'
title: '[Bug]: '
labels: ['Bug']
type: bug
body:
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What happened is...
    validations:
      required: true
  - type: checkboxes
    id: is-this-a-regression
    attributes:
      label: Is this a regression?
      description: Did this behavior work as intended in the previous version?
      options:
        - label: Yes, this issue did not exist in the previous version.
  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      description: List recommended steps to reproduce the error.
      placeholder: |
        1. Use x argument / navigate to
        2. Fill this information
        3. Go to...
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should be happening is...
    validations:
      required: true
  - type: upload
    id: attachments
    attributes:
      label: Attachment(s)
      description: If applicable, add screenshots or videos to help explain your problem.
    validations:
      accept: '.png,.jpg,.jpeg,.gif,.webp,.mp4,.mov,.webm'
  - type: input
    id: your-environment-os
    attributes:
      label: Your environment — OS
      description: The name and version of the operating system used when you encountered this issue.
      placeholder: (e.g., Windows 11, macOS Tahoe, Ubuntu 26.04 LTS, etc.)
    validations:
      required: true
  - type: input
    id: your-environment-browser
    attributes:
      label: Your environment — Browser
      description: The name and version of the web browser used when you encountered this issue (When applicable).
      placeholder: (e.g., Google Chrome 151, Mozilla Firefox 153, Safari 26, etc.)
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or additional information about the problem here.
      placeholder: It may be helpful to know that...
  - type: markdown
    attributes:
      value: |
        > [!CAUTION]
        > ### Please check open issues before submitting!
        > 📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛
        >
        > Oh, hi there! 😄
        >
        > To expedite issue processing, please search open and closed issues before submitting a new one.
        > Please read our Rules of Conduct at this repository's `.github/CODE_OF_CONDUCT.md`
        >
        > 📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛
