name: "🐞 Bug Report"
description: "Report an issue to help the project improve."
title: "[Bug]: "
labels: ["Bug"]
type: bug
body:
  - type: markdown
    attributes:
      value: | 
        # **🐞 Bug Report**
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: checkboxes
    id: is-this-a-regression
    attributes:
      label: Is this a regression?
      options:
        - label: Did this behaviour used to work in the previous version?
  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      description: List recommended steps to reproduce the error.
      placeholder: |
        1. Use x argument / navigate to
        2. Fill this information
        3. Go to...
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: upload
    id: attachments
    attributes:
      label: Attachment(s)
      description: If applicable, add screenshots or videos to help explain your problem.
    validations:
      accept: ".png,.jpg,.jpeg,.gif,.webp,.mp4,.mov,.webm"
  - type: textarea
    id: your-environment
    attributes:
      label: Your environment
      description: Use all the applicable bulleted list elements for this specific issue, and remove all the bulleted list elements that are not relevant for this issue.
      value: |
        * OS: <!--[e.g. Ubuntu 5.4.0-26-generic x86_64 / Windows 1904 ...]-->
        * Browser name and version:
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or additional information about the problem here.
  - type: markdown
    attributes:
      value: |
        📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛

        Oh, hi there! 😄

        To expedite issue processing, please search open and closed issues before submitting a new one.
        Please read our Rules of Conduct at this repository's `.github/CODE_OF_CONDUCT.md`

        📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛